version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-system-app
    depends_on:
      - mysql
      - redis
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "${PORT}:${PORT}"
    command: ./api

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:latest
    container_name: redis_store
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     - ENVIRONMENT=${ENVIRONMENT}
  #     - PROJECT_ROOT=${PROJECT_ROOT}
  #   command: go run cmd/db/main.go init
