version: '3.8'

services:
  mysql_test:
    image: mysql:latest
    container_name: mysql_db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis_test:
    image: redis:latest
    container_name: redis_store_test
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     - ENVIRONMENT=${ENVIRONMENT}
  #     - PROJECT_ROOT=${PROJECT_ROOT}
  #   command: go run cmd/db/main.go init
